config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #    URI                    controller | function shortcut
  #Todas as rotas a seguir serão resumidas em uma única rota
  #get("/blog_posts/new", to: "blog_posts#new", as: :new_blog_post) 
  #get("/blog_posts/:id", to: "blog_posts#show", as: :blog_post)
  #patch("/blog_posts/:id", to: "blog_posts#update")
  #delete("blog_posts/:id", to: "blog_posts#destroy")
  #get("blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post)
  #post("blog_posts", to: "blog_posts#create", as: :blog_posts)

  resources(:blog_posts)

  
  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action(:authenticate_user!, except: [:index, :show])
  before_action(:set_blog_post, except: [:index, :new, :create])

  def index 
    @blog_posts = BlogPost.all()
  end

  def show
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
  end

  def new
    @blog_post = BlogPost.new()
  end

  def create 
    @blog_post = BlogPost.new(blog_post_params())
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params())
      redirect_to @blog_post
    else
      render(:edit, status: :unprocessable_entity)
    end
  end

  def destroy
    @blog_post.destroy()
    redirect_to root_path
  end

  private

  def blog_post_params
    return params.require(:blog_post).permit(:title, :body) 
  end

  def set_blog_post
    @blog_post = BlogPost.find(params[:id])
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def create
    self.resource = warden.authenticate!(auth_options)
    if resource
      sign_in(resource_name, resource)
      flash[:notice] = "Signed in successfully."
      redirect_to root_path
    else
      flash[:alert] = "Invalid email or password."
      render :new
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with(model: blog_post, class: "flex flex-col") do |form| %>

  <%if form.object.errors.any?%>
    <div>
      <%form.object.errors.full_messages.each do |message|%>
        <div>
          <%=message%>
        </div>
      <%end%>
    </div>
  <%end%>

  <div class= "flex flex-col">
    <%=form.label :title%>
    <%=form.text_field :title%>
  </div>
  
  <div class= "flex flex-col">
    <%=form.label :body%>
    <%=form.text_area :body%>
  </div>

  <%=form.button(class: "bg-gray-100 px-4 py-2 rounded my-8 hover:bg-gray-200")%>

<%end%>

app/views/blog_posts/edit.html.erb
<h1>Edit a blog Post!</h1>
<%= render(partial: "form", locals: {blog_post: @blog_post}) %>

<%= button_to("Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"}, class: "bg-gray-100 px-4 py-2 rounded my-8 hover:bg-gray-200") %>
<%= link_to("Back", root_path, class:"no-underline hover:underline") %>

app/views/blog_posts/index.html.erb
<h1>Dev Journal</h1>
<hr class="my-8">
<% @blog_posts.each do |blog_post| %>
  <div>             <!- Texto        path -!>
    <h2><%= link_to(blog_post.title, blog_post_path(blog_post.id), class:"no-underline hover:underline") %></h2>
    <p><%= blog_post.body %></p>
  </div>
<%end%>

app/views/blog_posts/new.html.erb
<h1>Create a new Blog Post!</h1>
<%= render(partial: "form", locals: {blog_post: @blog_post}) %>
<%= link_to("Back", root_path, class:"no-underline hover:underline") %>

app/views/blog_posts/show.html.erb
<% if user_signed_in?() %>
  <%= link_to("Edit", edit_blog_post_path(@blog_post), class:"no-underline hover:underline") %>
<% end %>
<hr>
<h1><%= @blog_post.title %></h1>
<p><%= @blog_post.body %></p>
<%= link_to("Back", root_path, class:"no-underline hover:underline") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dev Journal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto px-8 py-8">

    <%= yield %>

    <hr class="my-8">
    <div>
    <% if user_signed_in?()%>
      <%= link_to("New Blog Post", new_blog_post_path, class:"no-underline my-16 hover:underline" ) %>
      <%#= link_to("Profile", edit_user_registration_path) %>
      <%= button_to("Log out", destroy_user_session_path, method: :delete, class: "bg-gray-100 px-4 py-2 rounded my-4 hover:bg-gray-200") %>
    <% elsif current_page?(root_path) %>
      <%=button_to("Log in", new_user_session_path, class: "bg-gray-100 px-4 py-2 rounded hover:bg-gray-200")%>
      <%#= link_to("Login", new_user_session_path) %>
      <%#= link_to("Sign up", new_user_registration_path) %>
    <% end %>
  </div>
  </body>
</html>